import type { Metadata } from 'next'
import { Exo } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'

const exo = Exo({ subsets: ['latin'], variable: '--font-exo' }) // Added Exo font

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={`${exo.variable}`} // Added Exo variable
			>
				<Navbar
					navItems={[
						{ name: 'About us', link: '/' },
						{ name: 'Charity', link: '/about' },
						{ name: 'Launchpad', link: '/about' },
					]}
				/>
				{children}
				<Footer />
			</body>
		</html>
	)
}
