import type { Metadata } from 'next'
import { Exo } from 'next/font/google'
import './globals.css'

const exo = Exo({ subsets: ['latin'], variable: '--font-exo' }) // Added Exo font

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={`${exo.variable}`} // Added Exo variable
			>
				{children}
			</body>
		</html>
	)
}
